#!/usr/bin/env python3
"""Authored mechanism tests, not external evidence. No model output is used."""
import argparse
import hashlib
import itertools
import json
import random
from pathlib import Path


def render(family, depth, positive):
    # Fixed alternating target decisions; chosen before model experiments.
    decisions = [i % 3 == 1 for i in range(depth)]
    target = sum((1 if take else -1) * 2**i for i, take in enumerate(decisions))
    lines = []
    if family == "loop":
        lines += ["int rand(void);", "int subject(void) {", "    int d=0, w=1;",
                  "    for(int i=0;i<%d;i++) {" % depth,
                  "        int x=rand();", "        if(x>0) d+=w; else d-=w;",
                  "        w*=2;", "    }"]
    elif family == "correlated":
        lines += ["int subject(int x) {", "    if(x<0 || x>=%d) return 0;" % (2**depth), "    int d=0;"]
        for i in range(depth):
            lines += ["    if(x%%%d >= %d) d+=%d; else d-=%d;" % (2**(i+1), 2**i, 2**i, 2**i)]
    else:
        lines += ["int subject(%s) {" % ", ".join("int x%d" % i for i in range(depth)), "    int d=0;"]
        for i in range(depth):
            lines += ["    if(x%d>0) d+=%d; else d-=%d;" % (i, 2**i, 2**i)]
    # A safe paired denominator is odd for every integral d; positive has one
    # branch vector with d==target. Ranges are tiny, so arithmetic cannot overflow.
    denominator = "d-(%d)" % target if positive else "2*d-(%d)" % (2*target+1)
    lines += ["    return 100/(%s);" % denominator, "}"]
    attainable = [sum((1 if bit else -1)*2**i for i,bit in enumerate(bits))
                  for bits in itertools.product((False, True), repeat=depth)]
    zeros = [d for d in attainable if (d-target if positive else 2*d-(2*target+1)) == 0]
    assert bool(zeros) == positive
    witness = ([int(take) for take in decisions] if family != "correlated" else
               [sum(2**i for i,take in enumerate(decisions) if take)])
    return "\n".join(lines)+"\n", {"decisions": decisions, "target": target,
            "attainable_d": attainable, "zero_values": zeros,
            "positive_initial_inputs": witness if positive else None}


def main():
    p=argparse.ArgumentParser();p.add_argument("--out",default="benchmarks/v3-diagnostic")
    args=p.parse_args();out=Path(args.out);(out/"sources").mkdir(parents=True,exist_ok=True)
    subjects=list(itertools.product(("independent","correlated","loop"),(3,5,7),(True,False)))
    random.Random(621503).shuffle(subjects)
    cases=[];labels=[]
    for index,(family,depth,positive) in enumerate(subjects,1):
        identity="d%03d" % index
        source,evidence=render(family,depth,positive)
        (out/"sources"/(identity+".c")).write_text(source)
        cases.append({"id":identity,"file":"sources/"+identity+".c","expected_bug":positive,
                      "category":family,"depth":depth,"sha256":hashlib.sha256(source.encode()).hexdigest()})
        labels.append({"id":identity,"family":family,"depth":depth,"expected_bug":positive,**evidence})
    (out/"manifest.json").write_text(json.dumps({"schema_version":3,"name":"v3-authored-diagnostic-18",
        "root":".","label_policy":"Analytic paired construction and exhaustive finite branch-vector enumeration; generated by project authors, not independent test data.",
        "cases":cases},indent=2)+"\n")
    (out/"label-evidence.json").write_text(json.dumps({"method":"Enumerate all 2**depth sign vectors; independent integers, bounded nonnegative x bits, or independent rand results realize every vector.","cases":labels},indent=2)+"\n")
    print("Generated",len(cases),"authored cases")


if __name__=="__main__": main()
